# Site settings
name: Matthew Ulmer
email: matt.d.ulmer@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, Data Engineer, Backend Engineer, GCP, Google Cloud, ETL, Data Pipeline, Python, Kubernetes, Java, Node.js, Agile, Pair Programming"
skills: "Sr. Software Engineer at FanAI"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/matthew-ulmer/
  - title: github
    url: https://github.com/Ulminator

links:
  companies:
    fanai:
      url: https://fan.ai
      backend: https://medium.com/fanai-engineering/the-backend-tech-stack-at-fanai-b48b4a61de19
    thd:
      url: https://www.homedepot.com
      award: "../img/teamAward.jpg"
  education:
    emory: https://www.emory.edu
  certifications:
    gcp: https://www.credential.net/41e63b14-6fb9-49c4-b864-a310cf3b2dfc
    cka: "../img/cka.pdf"
  internships:
    sfl: https://sflscientific.com
    simbiosys: https://simbiosys.mathcs.emory.edu/
    vichf: https://nsf-cchf.com/vichf/vic-hf-ireu-international-research-experience-for-undergraduates
  football:
    max_preps: https://www.maxpreps.com/athlete/matt-ulmer/hVjr8vTxEeKZ5AAmVebBJg/default.htm
    award: "../img/footballAward.jpg"

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
# color:
#   primary: 2196F3
#   primary-rgb: "33, 150, 243"
#   secondary: 285172
#   secondary-dark: 29455b
#   section-tout: eaf1f1

# Great for color scheme help (https://coolors.co/)

color:
  primary: 43C6B9
  primary-rgb: "174, 66, 78"
  secondary: "294A4C"
  secondary-dark: "182C2D"
  section-tout: eaf1f1


# Build settings
markdown: kramdown
permalink: pretty


exclude:
  - .jekyll-cache