# Site settings
name: Matthew Ulmer
email: matt.d.ulmer@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, Data Engineer, Backend Engineer, GCP, Google Cloud, ETL, Data Pipeline, Python, Java, Node.js, Agile, Pair Programming"
skills: "Backend/Data Engineer at FanAI"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/matthew-ulmer/
  - title: github
    url: https://github.com/Ulminator
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
# color:
#   primary: 2196F3
#   primary-rgb: "33, 150, 243"
#   secondary: 285172
#   secondary-dark: 29455b
#   section-tout: eaf1f1

# Great for color scheme help (https://coolors.co/)

color:
  primary: 43C6B9
  primary-rgb: "174, 66, 78"
  secondary: "294A4C"
  secondary-dark: "182C2D"
  section-tout: eaf1f1


# Build settings
markdown: kramdown
permalink: pretty


exclude:
  - .jekyll-cache